include:
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml

stages:
  - test
  - build
  - scan

.common:
  tags:
    - docker

#### TEST ####
secret_detection:
  tags:
    - docker

semgrep-sast:
  tags:
    - docker

#### BUILD ####
.common:build:
  stage: build
  extends:
    - .common

build:
  extends:
    - .common:build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  before_script:
    - echo "$ENV_VAR" > "$CI_PROJECT_DIR/.env"
    - mkdir -p /kaniko/.docker
    - |
      cat <<EOF > /kaniko/.docker/config.json
      {
        "auths": {
          "$CI_REGISTRY": {
            "username": "$CI_REGISTRY_USER",
            "password": "$CI_REGISTRY_PASSWORD"
          }
        }
      }
      EOF
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"

#### SCAN ####
container_scanning:
  stage: scan
  tags:
    - docker
  variables:
    SECURE_LOG_LEVEL: 'debug'
  before_script:
    - export CS_IMAGE=${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
