# This is a basic workflow to help you get started with Actions
name: Docker Image CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # This workflow contains multiple jobs
  build_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      # install applicaion dependencies
      - name: Install dependencies
        run: |
          npm install

      # build and test the apps
      - name: build
        run: |
          npm run build
          npm test
          
  push_to_Docker_Hub:

    runs-on: ubuntu-latest
    # build docker image and push to docker hub
    # only if the app build and test successfully
    needs: [build_test]
    steps:
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag alexandravasilie/bookstore-backend:latest
      
      - name: Docker Push
        run: docker push ${{secrets.DOCKER_USER}}/bookstore-backend:latest
        
